version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insurance_api
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DEFAULT_CURRENCY=USD
      - INSURANCE_BASE_RATE=0.005
      - INSURANCE_COVERAGE_PERCENTAGE=1.0
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"